### ISSUE TITLE
类GW809Server的93行 报错

### ISSUE THREAD

**Issue by Jeadren** [jjaaddiicc/gpsGW809#3]
类GW809Server的93行 报错

 /**************************信息交互业务下发******************************/
        loadPlatDataTimer = new KKSimpleTimer(new ThreadPlatLoadData(threadSendPlatData, dataLoadedSingal), 5, Const.LOAD_GPS_DATA_INTERVAL_SECONDS);

**Comment by jjaaddiicc** [comment]
确认下相关编译环境吧
